version: "3.7"

services:

  builder:
    image: builder
    build: .

  login:
    build: docker/login_server
    depends_on:
      - db
    ports:
      - 3724:3724

  realm:
    build: docker/realm_server
    depends_on:
      - db
      - login
    ports:
      - 6279:6279

  # world:
  #   build: docker/world_server
  #   depends_on:
  #     - builder
  #     - db
  #   ports:
  #     - 8080:8080

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./docker/mysql/init/01_create_databases.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./data/login/login_db_schema_full.sql:/docker-entrypoint-initdb.d/02_login_schema.sql
      - ./data/realm/realm_db_schema_full.sql:/docker-entrypoint-initdb.d/03_realm_schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_USER: mmo
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
